#!/bin/bash

CONFIG=/boot/firmware/config.txt
SERIAL_NUM=0

while getopts 'd' opt; do
  case "$opt" in
    d) DEV=true
    ;;
  esac
done

# install pyVISA (required systemwide)
sudo apt-get -y install python3-pyvisa python3-pyvisa-py

if [[ -n $DEV ]]; then
  echo "development mode enabled: installing dev tools"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

# authorize user for raw usb access
echo "Creating USB udev rules"
sudo groupadd afpusb
sudo usermod -aG afpusb $USER

# create udev rule
cat << EOF | sudo tee /etc/udev/rules.d/99-afpusb.rules
SUBSYSTEM=="usb", GROUP="afpusb", MODE="0666"
EOF

# reload udev
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Setting up UART"
sudo raspi-config nonint do_serial_cons 1
sudo raspi-config nonint do_serial_hw 0
cat << EOF | sudo tee -a $CONFIG
dtoverlay=disable-bt
EOF

echo "Setting hostname"
sudo raspi-config nonint do_hostname "tekafp-$SERIAL_NUM"


read -p "Setup complete. Would you like to reboot? [y/n]: " setup_reboot

if [[ "$setup_reboot" == "y" ]]; then
  sudo reboot
fi
